#8378 - new Excel commands described
G1ANT-Robot/G1ANT.Addon.MsOffice pull request #10
Opened 2019-07-17 15:13 UTC by Vegebutcher

copy, paste, selectrange

2019-07-17 15:15 UTC, WiktoriaPrusik requested changes

2019-07-17 15:15 UTC, WiktoriaPrusik commented on G1ANT.Addon.MSOffice/Commands/ExcelCopyCommand.md
> +| `timeout`      | [timespan](https://manual.g1ant.com/link/G1ANT.Language/G1ANT.Language/Structures/TimeSpanStructure.md) | no       | [♥timeoutcommand](https://manual.g1ant.com/link/G1ANT.Language/
incorrect link https://manual.g1ant.com/link/G1ANT.Language/G1ANT.Addon.Core/Variables/TimeoutCommandVariable.md

2019-07-17 15:15 UTC, WiktoriaPrusik commented on G1ANT.Addon.MSOffice/Commands/ExcelPasteCommand.md
> +| `timeout`      | [timespan](https://manual.g1ant.com/link/G1ANT.Language/G1ANT.Language/Structures/TimeSpanStructure.md) | no       | [♥timeoutcommand](https://manual.g1ant.com/link/G1ANT.Language/
same

2019-07-17 15:15 UTC, WiktoriaPrusik commented on G1ANT.Addon.MSOffice/Commands/ExcelSelectRangeCommand.md
> +| `timeout`      | [timespan](https://manual.g1ant.com/link/G1ANT.Language/G1ANT.Language/Structures/TimeSpanStructure.md) | no       | [♥timeoutcommand](https://manual.g1ant.com/link/G1ANT.Language/
same

2019-07-17 15:27 UTC, Vegebutcher commented on G1ANT.Addon.MSOffice/Commands/ExcelCopyCommand.md
> +| `timeout`      | [timespan](https://manual.g1ant.com/link/G1ANT.Language/G1ANT.Language/Structures/TimeSpanStructure.md) | no       | [♥timeoutcommand](https://manual.g1ant.com/link/G1ANT.Language/
```suggestion
| `timeout`      | [timespan](https://manual.g1ant.com/link/G1ANT.Language/G1ANT.Language/Structures/TimeSpanStructure.md) | no       | [♥timeoutcommand](https://manual.g1ant.com/link/G1ANT.Addon.Core/G1ANT.Addon.Core/Variables/TimeoutCommandVariable.md) | Specifies time in milliseconds for G1ANT.Robot to wait for the command to be executed |
```

2019-07-17 15:28 UTC, Vegebutcher commented on G1ANT.Addon.MSOffice/Commands/ExcelPasteCommand.md
> +| `timeout`      | [timespan](https://manual.g1ant.com/link/G1ANT.Language/G1ANT.Language/Structures/TimeSpanStructure.md) | no       | [♥timeoutcommand](https://manual.g1ant.com/link/G1ANT.Language/
```suggestion
| `timeout`      | [timespan](https://manual.g1ant.com/link/G1ANT.Language/G1ANT.Language/Structures/TimeSpanStructure.md) | no       | [♥timeoutcommand](https://manual.g1ant.com/link/G1ANT.Addon.Core/G1ANT.Addon.Core/Variables/TimeoutCommandVariable.md) | Specifies time in milliseconds for G1ANT.Robot to wait for the command to be executed |
```

2019-07-17 15:28 UTC, Vegebutcher commented on G1ANT.Addon.MSOffice/Commands/ExcelSelectRangeCommand.md
> +| `timeout`      | [timespan](https://manual.g1ant.com/link/G1ANT.Language/G1ANT.Language/Structures/TimeSpanStructure.md) | no       | [♥timeoutcommand](https://manual.g1ant.com/link/G1ANT.Language/
```suggestion
| `timeout`      | [timespan](https://manual.g1ant.com/link/G1ANT.Language/G1ANT.Language/Structures/TimeSpanStructure.md) | no       | [♥timeoutcommand](https://manual.g1ant.com/link/G1ANT.Addon.Core/G1ANT.Addon.Core/Variables/TimeoutCommandVariable.md) | Specifies time in milliseconds for G1ANT.Robot to wait for the command to be executed |
```

2019-07-18 10:20 UTC, WiktoriaPrusik approved these changes

2019-07-18 10:21 UTC, merged